### ISSUE TITLE
目前有遇到ios手机生成不了吗？

### ISSUE THREAD

**Issue by xiabuyuanyu** [qbhy/poster-generater#4]
我试了好几个插件，比如iphone 6 plus 不行，安卓小米8有时不行等问题
在测试那里换了下图，报这个
![image](https://user-images.githubusercontent.com/25945540/66999326-5c2d0f00-f108-11e9-87ec-bbf66161a8b7.png)

**Comment by qbhy** [comment]
测试服已经过期了，建议自己部署测试
