### ISSUE TITLE
希望能增加阿里云oss支持

### ISSUE THREAD

**Issue by q876625596** [qbhy/poster-generater#7]
插件非常好用，但因为公司是使用的阿里云的oss，所以希望作者能在以后的版本提供阿里云支持的配置，非常感谢！

**Comment by qbhy** [comment]
已经添加阿里云 oss 上传组件支持。
@q876625596 
https://github.com/qbhy/poster-generater/commit/ed883224aa9572bf3bfaf91d623ed04e8a306118
